version: '2'

services:
  eureka:
    build: eureka-server/.
    ports:
      - "7777:7777"
  db:
    build: ignite-server/.
    ports:
      - "11000:10000"
  web:
    build: addressbook-main/.
    ports:
      - "10000:9000"